### ISSUE TITLE
Unable to set proxy

### ISSUE THREAD

**Issue by Pimeau** [dirkbonhomme/pusher-client-node#11]
Hello,

The reason I'm submitting this as an issue is that you want to maintain compatibility to the official pusher client, and pusher-client-node does not allow for setting a proxy. Since I work behind a corportate proxy, this has been a real headache, and I bet there are more people in the same situtation. I gave it a shot myself but I am not that knowledgeable.

Thanks in advance,
Pimeau

**Comment by dirkbonhomme** [comment]
Hi @Pimeau 

Thanks for creating the ticket. I can't find anything about proxies in the PusherJS docs so not sure how I should fix this. Do you have an example of how you configure the official client?

**Comment by Pimeau** [comment]
Hello Dirk,

Thanks for your reply. My bad, I was looking at
https://github.com/pusher/pusher-http-node, which a colleague told me was
the official client. This one lets you set a proxy, but now I'm confused,
what is the official client? :|

It would be great if you could support proxies. We're behind a corportate
one without much control over server or network configuration. I was
tinkering with your code but I'm far too newbie for getting it working.

Excuse me if I created a defect out of something that is not.

Best regards,
Luis M

**Comment by dirkbonhomme** [comment]
The "pusher-js" library is Pusher's official client to consume their realtime data channels and meant to be used in a browser: https://github.com/pusher/pusher-js

This "pusher-client-node" library is a port of Pusher's official client and meant to be used in Nodejs environments

The "pusher-http-node" is Pusher's official library to communicate with their API, not the realtime data channels.

So not sure what you are trying to do? Use their api or consume realtime data? There might be an easy way to pass your proxy settings to the underlying library I'm using. But guess I'll need an example first.

**Comment by Pimeau** [comment]
We are listening on their realtime data channels for the new_lead event.
Based on that we trigger some actions.

When I was tinkering with your code, I hard-coded a proxy in the
requestOptions variable the WebSocket uses. Before my experiments, we
usually get:

Error { type: 'WebSocketError',
error: 'Unknown socket error: ETIMEDOUT connect' }

After that:
Error { type: 'WebSocketError',
error: 'Unknown socket error: EPROTO write'

This is what I did to requestOptions:
  var requestOptions = {
    port: 8080,
    host: 'OUR_PROXY',
    path: 'wss://ws.pusherapp.com:' + port,
    headers: {
      'Connection': 'Upgrade',
      'Upgrade': 'websocket',
      'Host': headerHost,
      'Sec-WebSocket-Version': options.value.protocolVersion,
      'Sec-WebSocket-Key': key
    }
  };

Later on the path would be concatenated (+=) with the rest of the URL, I
read somewhere that this is how you could achieve using a proxy, but I sure
messed up. I tried both encrypted true / false when creating the Pusher
object but nothing changes.

Please let me know if you need more details.

**Comment by dirkbonhomme** [comment]
I think you are on the right track but I'm afraid that's as far as I can help you. I'm not sure if and how a websocket proxy is supposed to work. From the looks of it I would guess that you are using an http proxy (port 8080..) which probably isn't able to forward websockets.

You might have more luck asking it over at the "ws" library? https://github.com/websockets/ws

Success!

**Comment by Pimeau** [comment]
Makes total sense Dirk, it boils down to the ws lib. I will continue my
research with the guys there. Thanks for taking the time to reply to my
mails. Your last name suits you well :-)

Merci bien,
Luis M

**Comment by dirkbonhomme** [comment]
Haha thanks. Let me know if you've been able to figure it out. There might be an easy way to enable proxies through this plugin's configuration. I'll close the ticket for now.
