### ISSUE TITLE
Uncaught SyntaxError: Failed to construct 'WebSocket': The subprotocol '[object Object]' is invalid.

### ISSUE THREAD

**Issue by Flugund** [dirkbonhomme/pusher-client-node#4]
Uncaught SyntaxError: Failed to construct 'WebSocket': The subprotocol '[object Object]' is invalid. Message is generated when I create a new Object of Pusher.

Code: 
```javascript
var pusher = new Pusher(API_KEY);
var channel = pusher.subscribe('test_channel');
channel.bind('my_event', function(data) {
    alert(data.message);
});
```

**Comment by dirkbonhomme** [comment]
Hi Fabian

Can you verify the following:

- npm install finished successfully?
- what version of node.js (io.js?) are you using?
- does the exception return more details like filename or line number?

**Comment by davidnorth** [comment]
Same here. I get this error in Chrome but in the node console it works fine.

**Comment by naorye** [comment]
Same here.

**Comment by dirkbonhomme** [comment]
@davidnorth @naorye can you test the following things please?

- npm install finished successfully?
- what version of node.js (io.js?) are you using?
- does the exception return more details like filename or line number?

**Comment by jtremback** [comment]
- Yes
- Error is in Chrome, using Browserify for modules
- Screenshot:
![image](https://cloud.githubusercontent.com/assets/1335122/6886914/175ad52a-d604-11e4-807a-e7277e3bf35d.png)

**Comment by naorye** [comment]
Soon Pusher will release this: https://github.com/pusher/pusher-js/issues/84

**Comment by leggetter** [comment]
pusher-js is for web browser runtimes only.

**Comment by Alex-DE-74** [comment]
Any progress on this issue?
Need to pass properties in order to use WSS with self-signed-certificate, but get this exception.
Code for socket creation:
```
var address = 'wss://localhost:443';
var socket = new WebSocket(address, {
  protocolVersion: 8,
  rejectUnauthorized: false,
  origin: 'https://localhost:443',
  strictSSL: false
});
```

**Comment by dirkbonhomme** [comment]
@Alex-DE-74 Are you sure your question belongs to this pusher-client-node library? Looks like you're trying to use a Websocket library directly. Perhaps https://github.com/websockets/ws ?

**Comment by mhkarimi** [comment]
same here. its a little bit strange.
I am getting the same error on Chrome , though I used this : 
```
 this.ws = new WebSocket(
            ws://localhost:8082?name,["mh", "3gn11Ft0Me8lkqqW2sasas"]
        );
```
but when I tried that with firefox, it was OK

**Comment by mhkarimi** [comment]
I have solved this by adding a header as below to the http response in back-end part : 
 key = "Sec-WebSocket-Protocol" and value of one of your protocols
