### ISSUE TITLE
How to disconnect and exit?

### ISSUE THREAD

**Issue by hotpxl** [dirkbonhomme/pusher-client-node#7]
Hi.

I have something like this.

```
var socket = new Pusher('abc');
socket.disconnect();
```

But it's preventing Node from exiting. Is there a way to terminate?

**Comment by dirkbonhomme** [comment]
I don't think a disconnect will cleanup event listeners on channels, preventing Node to shut down by itself. You will probably have to do something like https://nodejs.org/api/events.html#events_emitter_removealllisteners_event

```
channels.forEach(function(channel){
   channel. removeAllListeners();
});
```

Or, if you want your app to exit you can just do

```
var socket = new Pusher('abc');
socket.disconnect();
process.exit();
```

or even 

```
var socket = new Pusher('abc');
process.exit();
```

**Comment by dirkbonhomme** [comment]
@hotpxl Have you been able to figure it out? Let me know if you need more help

**Comment by hotpxl** [comment]
Yes. Thanks very much!
