### ISSUE TITLE
Account over quota trying to connect to pusher

### ISSUE THREAD

**Issue by pabx06** [dirkbonhomme/pusher-client-node#9]
hello. here is what i did:

i have tried to mimic this webpage that use the pusher-client for webbrowser : https://www.bitstamp.net/s/examples/live_diff_order_book.html

`var Pusher = require('pusher-client');`
`var pusher = new Pusher('de504dc5763aeef9ff52');`
`var bitstamp_orderbook_channel = pusher.subscribe('diff_order_book');`

what i get `{ event: 'pusher:error',
  data: { code: 4004, message: 'Account over quota' } }
trying connecting to pusher on - wss://ws.pusherapp.com:443/app/cb65d0a7a72cd94adf1f?client=node-pusher-server&version=0.0.1&protocol=5&flash=false`

**Comment by dirkbonhomme** [comment]
Hi @pabx06 

I think your account temporarily reached its allowed quota. I've just tested it and appears to be working fine :)

Let me know if it's resolved so I can close this ticket

**Comment by dirkbonhomme** [comment]
Please reopen this issue if you have more information :)
